### ISSUE TITLE
UnrealBuildTool error

### ISSUE THREAD

**Issue by iperov** [Noesis/UE4Plugin#14]
```
UnrealBuildTool.GuardedMain: Command line: 
D:\EpicGames\UE_4.21\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Editor Win64 Development -iwyu -nocreatestub -NoHotReload -module=NoesisRuntime -module=NoesisEditor -project=D:\devBsfgUE4\TestNoesisGUI\TestNoesisGUI.uproject
UnrealBuildTool.RunUBT: Creating makefile for UE4Editor (no existing makefile)
Log.WriteException: ==============================================================================
Log.WriteException: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
Log.WriteException:           at Tools.DotNETCommon.FileSystemReference.CombineStrings(DirectoryReference BaseDirectory, String[] Fragments) in D:\Build\++UE4\Sync\Engine\Saved\CsTools\Engine\Source\Programs\DotNETCommon\DotNETUtilities\FileSystemReference.cs:line 56
Log.WriteException:           at Tools.DotNETCommon.DirectoryReference.Combine(DirectoryReference BaseDirectory, String[] Fragments) in D:\Build\++UE4\Sync\Engine\Saved\CsTools\Engine\Source\Programs\DotNETCommon\DotNETUtilities\DirectoryReference.cs:line 155
Log.WriteException:           at UnrealBuildTool.ProjectFileGenerator.GetPreferredSourceCodeAccessor(FileReference ProjectFile, ProjectFileFormat& Format) in D:\Build\++UE4\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\ProjectFileGenerator.cs:line 521
Log.WriteException:           at UnrealBuildTool.WindowsPlatform.GetDefaultCompiler(FileReference ProjectFile) in D:\Build\++UE4\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Platform\Windows\UEBuildWindows.cs:line 554
Log.WriteException:           at UnrealBuildTool.WindowsPlatform.ValidateTarget(TargetRules Target) in D:\Build\++UE4\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Platform\Windows\UEBuildWindows.cs:line 461
Log.WriteException:           at UnrealBuildTool.UEBuildTarget.CreateTarget(TargetDescriptor Desc, String[] Arguments, Boolean bSkipRulesCompile, Boolean bCompilingSingleFile, Boolean bUsePrecompiled, ReadOnlyBuildVersion Version) in D:\Build\++UE4\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 467
Log.WriteException:           at UnrealBuildTool.UnrealBuildTool.RunUBT(BuildConfiguration BuildConfiguration, String[] Arguments, FileReference ProjectFile, Boolean bCatchExceptions) in D:\Build\++UE4\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 1426
Log.WriteException:        (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)
```

**Comment by iperov** [comment]
my bad
